<a href="https://colab.research.google.com/github/Geetanjali501/ML-OPS/blob/main/MLops_Feast.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip -q install feast==0.64.0 pyarrow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 66.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 19.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.2/137.2 kB 11.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 16.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 89.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 55.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 kB 28.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 3.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.4.0 requires tenacity<10,>=9, but you have tenacity 8.5.0 which is incompatible.

In [2]:
import feast
print("Feast version:", feast.__version__)

Feast version: 0.64.0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [4]:
from google.colab import files
uploaded = files.upload()

Saving balanced_employability_dataset.csv to balanced_employability_dataset.csv

In [5]:
import pandas as pd
df = pd.read_csv("balanced_employability_dataset.csv")
print(df.head())
print(df.shape)

   Student_ID  Age  Gender  CGPA  Attendance  Programming  Data_Structures  \
0        1001   23       1  8.14          84           41               47
1        1002   24       1  8.85          95           88               52
2        1003   22       1  7.44          86           52               47
3        1004   24       0  6.07          97           43               96
4        1005   24       1  6.78          66           65               62

   Algorithms  DBMS  Operating_Systems  ...  Problem_Solving  Teamwork  \
0          49    92                 47  ...               49        85
1          73    84                 93  ...               63        63
2          55    51                 91  ...               57        73
3          87   100                 59  ...               88        85
4          90    87                 71  ...               57        61

   Internship  Projects  Certifications  Aptitude  Average_Skill  \
0           0         2               2        98          69.53
1           0         4               5        58          74.94
2           1         5               2       100          66.18
3           0         3               0        99          74.18
4           0         2               4        72          67.82

   Industry_Requirement  Skill_Gap  Employability
0                    89      19.47              0
1                    87      12.06              1
2                    86      19.82              1
3                    75       0.82              1
4                    77       9.18              0

[5 rows x 30 columns]
(694, 30)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [6]:
print(df.columns)
print(df.info())
print(df.isnull().sum())

Index(['Student_ID', 'Age', 'Gender', 'CGPA', 'Attendance', 'Programming',
       'Data_Structures', 'Algorithms', 'DBMS', 'Operating_Systems',
       'Computer_Networks', 'OOP', 'Python', 'Java', 'SQL', 'Web_Development',
       'Git_GitHub', 'Cloud_Computing', 'AI_ML', 'Communication',
       'Problem_Solving', 'Teamwork', 'Internship', 'Projects',
       'Certifications', 'Aptitude', 'Average_Skill', 'Industry_Requirement',
       'Skill_Gap', 'Employability'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 694 entries, 0 to 693
Data columns (total 30 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Student_ID            694 non-null    int64
 1   Age                   694 non-null    int64
 2   Gender                694 non-null    int64
 3   CGPA                  694 non-null    float64
 4   Attendance            694 non-null    int64
 5   Programming           694 non-null    int64
 6   Data_Structures       694 non-null    int64
 7   Algorithms            694 non-null    int64
 8   DBMS                  694 non-null    int64
 9   Operating_Systems     694 non-null    int64
 10  Computer_Networks     694 non-null    int64
 11  OOP                   694 non-null    int64
 12  Python                694 non-null    int64
 13  Java                  694 non-null    int64
 14  SQL                   694 non-null    int64
 15  Web_Development       694 non-null    int64
 16  Git_GitHub            694 non-null    int64
 17  Cloud_Computing       694 non-null    int64
 18  AI_ML                 694 non-null    int64
 19  Communication         694 non-null    int64
 20  Problem_Solving       694 non-null    int64
 21  Teamwork              694 non-null    int64
 22  Internship            694 non-null    int64
 23  Projects              694 non-null    int64
 24  Certifications        694 non-null    int64
 25  Aptitude              694 non-null    int64
 26  Average_Skill         694 non-null    float64
 27  Industry_Requirement  694 non-null    int64
 28  Skill_Gap             694 non-null    float64
 29  Employability         694 non-null    int64
dtypes: float64(3), int64(27)
memory usage: 162.8 KB
None
Student_ID              0
Age                     0
Gender                  0
CGPA                    0
Attendance              0
Programming             0
Data_Structures         0
Algorithms              0
DBMS                    0
Operating_Systems       0
Computer_Networks       0
OOP                     0
Python                  0
Java                    0
SQL                     0
Web_Development         0
Git_GitHub              0
Cloud_Computing         0
AI_ML                   0
Communication           0
Problem_Solving         0
Teamwork                0
Internship              0
Projects                0
Certifications          0
Aptitude                0
Average_Skill           0
Industry_Requirement    0
Skill_Gap               0
Employability           0
dtype: int64

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [8]:
import pandas as pd

df["student_id"] = df["Student_ID"].astype("int64")

df["cgpa"] = df["CGPA"].astype("float32")
df["attendance"] = df["Attendance"].astype("float32")

df["programming"] = df["Programming"].astype("float32")
df["data_structures"] = df["Data_Structures"].astype("float32")
df["algorithms"] = df["Algorithms"].astype("float32")
df["dbms"] = df["DBMS"].astype("float32")
df["operating_systems"] = df["Operating_Systems"].astype("float32")
df["computer_networks"] = df["Computer_Networks"].astype("float32")
df["oop"] = df["OOP"].astype("float32")
df["python"] = df["Python"].astype("float32")
df["java"] = df["Java"].astype("float32")
df["sql"] = df["SQL"].astype("float32")
df["web_development"] = df["Web_Development"].astype("float32")

df["git_github"] = df["Git_GitHub"].astype("float32")
df["cloud_computing"] = df["Cloud_Computing"].astype("float32")
df["ai_ml"] = df["AI_ML"].astype("float32")

df["communication"] = df["Communication"].astype("float32")
df["problem_solving"] = df["Problem_Solving"].astype("float32")
df["teamwork"] = df["Teamwork"].astype("float32")

df["internship"] = df["Internship"].astype("int64")
df["projects"] = df["Projects"].astype("int64")
df["certifications"] = df["Certifications"].astype("int64")
df["aptitude"] = df["Aptitude"].astype("float32")

df["average_skill"] = df["Average_Skill"].astype("float32")
df["industry_requirement"] = df["Industry_Requirement"].astype("float32")
df["skill_gap"] = df["Skill_Gap"].astype("float32")

df["Gender"] = df["Gender"].astype(str).str.strip().str.lower()

df["gender_encoded"] = df["Gender"].map({
    "male": 0,
    "female": 1
})

df["gender_encoded"] = df["gender_encoded"].fillna(0).astype("int64")

df["employability"] = df["Employability"].astype("int64")

print(df.head())

   Student_ID  Age Gender  CGPA  Attendance  Programming  Data_Structures  \
0        1001   23      1  8.14          84           41               47
1        1002   24      1  8.85          95           88               52
2        1003   22      1  7.44          86           52               47
3        1004   24      0  6.07          97           43               96
4        1005   24      1  6.78          66           65               62

   Algorithms  DBMS  Operating_Systems  ...  teamwork  internship  projects  \
0          49    92                 47  ...      85.0           0         2
1          73    84                 93  ...      63.0           0         4
2          55    51                 91  ...      73.0           1         5
3          87   100                 59  ...      85.0           0         3
4          90    87                 71  ...      61.0           0         2

   certifications  aptitude  average_skill  industry_requirement  skill_gap  \
0               2      98.0      69.529999                  89.0  19.469999
1               5      58.0      74.940002                  87.0  12.060000
2               2     100.0      66.180000                  86.0  19.820000
3               0      99.0      74.180000                  75.0   0.820000
4               4      72.0      67.820000                  77.0   9.180000

   gender_encoded  employability
0               0              0
1               0              1
2               0              1
3               0              1
4               0              0

[5 rows x 59 columns]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [9]:
df[
    [
        "student_id",
        "gender_encoded",
        "cgpa",
        "attendance",
        "programming",
        "data_structures",
        "algorithms",
        "dbms",
        "operating_systems",
        "computer_networks",
        "oop",
        "python",
        "java",
        "sql",
        "web_development",
        "git_github",
        "cloud_computing",
        "ai_ml",
        "communication",
        "problem_solving",
        "teamwork",
        "internship",
        "projects",
        "certifications",
        "aptitude",
        "average_skill",
        "industry_requirement",
        "skill_gap",
        "employability"
    ]
].head()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,student_id,gender_encoded,cgpa,attendance,programming,data_structures,algorithms,dbms,operating_systems,computer_networks,...,problem_solving,teamwork,internship,projects,certifications,aptitude,average_skill,industry_requirement,skill_gap,employability
0,1001,0,8.14,84.0,41.0,47.0,49.0,92.0,47.0,92.0,...,49.0,85.0,0,2,2,98.0,69.529999,89.0,19.469999,0
1,1002,0,8.85,95.0,88.0,52.0,73.0,84.0,93.0,69.0,...,63.0,63.0,0,4,5,58.0,74.940002,87.0,12.060000,1
2,1003,0,7.44,86.0,52.0,47.0,55.0,51.0,91.0,74.0,...,57.0,73.0,1,5,2,100.0,66.180000,86.0,19.820000,1
3,1004,0,6.07,97.0,43.0,96.0,87.0,100.0,59.0,74.0,...,88.0,85.0,0,3,0,99.0,74.180000,75.0,0.820000,1
4,1005,0,6.78,66.0,65.0,62.0,90.0,87.0,71.0,88.0,...,57.0,61.0,0,2,4,72.0,67.820000,77.0,9.180000,0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [13]:
base_time = pd.Timestamp(
    "2026-01-01",
    tz="UTC"
)

df["event_timestamp"] = (
    base_time +
    pd.to_timedelta(
        df["student_id"],
        unit="s"
    )
)

df["created_timestamp"] = (
    df["event_timestamp"] +
    pd.Timedelta(seconds=1)
)

In [16]:
feature_df = df[
    [
        "student_id",
        "event_timestamp",
        "created_timestamp",
        "gender_encoded",
        "cgpa",
        "attendance",
        "programming",
        "data_structures",
        "algorithms",
        "dbms",
        "operating_systems",
        "computer_networks",
        "oop",
        "python",
        "java",
        "sql",
        "web_development",
        "git_github",
        "cloud_computing",
        "ai_ml",
        "communication",
        "problem_solving",
        "teamwork",
        "internship",
        "projects",
        "certifications",
        "aptitude",
        "average_skill",
        "industry_requirement",
        "skill_gap"
    ]
].copy()

label_df = df[
    [
        "student_id",
        "event_timestamp",
        "employability"
    ]
].copy()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [17]:
print("Feature data:")
display(feature_df.head())
print("Labels:")
display(label_df.head())

Feature data:

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,student_id,event_timestamp,created_timestamp,gender_encoded,cgpa,attendance,programming,data_structures,algorithms,dbms,...,communication,problem_solving,teamwork,internship,projects,certifications,aptitude,average_skill,industry_requirement,skill_gap
0,1001,2026-01-01 00:16:41+00:00,2026-01-01 00:16:42+00:00,0,8.14,84.0,41.0,47.0,49.0,92.0,...,45.0,49.0,85.0,0,2,2,98.0,69.529999,89.0,19.469999
1,1002,2026-01-01 00:16:42+00:00,2026-01-01 00:16:43+00:00,0,8.85,95.0,88.0,52.0,73.0,84.0,...,95.0,63.0,63.0,0,4,5,58.0,74.940002,87.0,12.060000
2,1003,2026-01-01 00:16:43+00:00,2026-01-01 00:16:44+00:00,0,7.44,86.0,52.0,47.0,55.0,51.0,...,81.0,57.0,73.0,1,5,2,100.0,66.180000,86.0,19.820000
3,1004,2026-01-01 00:16:44+00:00,2026-01-01 00:16:45+00:00,0,6.07,97.0,43.0,96.0,87.0,100.0,...,68.0,88.0,85.0,0,3,0,99.0,74.180000,75.0,0.820000
4,1005,2026-01-01 00:16:45+00:00,2026-01-01 00:16:46+00:00,0,6.78,66.0,65.0,62.0,90.0,87.0,...,54.0,57.0,61.0,0,2,4,72.0,67.820000,77.0,9.180000

Labels:

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

   student_id           event_timestamp  employability
0        1001 2026-01-01 00:16:41+00:00              0
1        1002 2026-01-01 00:16:42+00:00              1
2        1003 2026-01-01 00:16:43+00:00              1
3        1004 2026-01-01 00:16:44+00:00              1
4        1005 2026-01-01 00:16:45+00:00              0

In [18]:
import os

repo_path = "/content/employability_feast"

os.makedirs(
    f"{repo_path}/data",
    exist_ok=True
)

In [19]:
feature_df.to_parquet(
    f"{repo_path}/data/employability_features.parquet",
    index=False
)

In [20]:
feature_store_yaml = """
project: employability_project

registry: data/registry.db

provider: local

offline_store:
  type: file

online_store:
  type: sqlite
  path: data/online_store.db
"""

with open(
    f"{repo_path}/feature_store.yaml",
    "w"
) as f:
    f.write(feature_store_yaml)

In [21]:
feature_definition = '''
from datetime import timedelta

from feast import (
    Entity,
    FeatureView,
    FeatureService,
    Field,
    FileSource
)

from feast.types import (
    Float32,
    Int64
)

student = Entity(
    name="student",
    join_keys=["student_id"],
    description="CSE student"
)

employability_source = FileSource(
    name="employability_source",
    path="data/employability_features.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp"
)

employability_feature_view = FeatureView(
    name="employability_features",
    entities=[student],

    ttl=timedelta(days=50000),

    schema=[
        Field(name="gender_encoded", dtype=Int64),
        Field(name="cgpa", dtype=Float32),
        Field(name="attendance", dtype=Float32),
        Field(name="programming", dtype=Float32),
        Field(name="data_structures", dtype=Float32),
        Field(name="algorithms", dtype=Float32),
        Field(name="dbms", dtype=Float32),
        Field(name="operating_systems", dtype=Float32),
        Field(name="computer_networks", dtype=Float32),
        Field(name="oop", dtype=Float32),
        Field(name="python", dtype=Float32),
        Field(name="java", dtype=Float32),
        Field(name="sql", dtype=Float32),
        Field(name="web_development", dtype=Float32),
        Field(name="git_github", dtype=Float32),
        Field(name="cloud_computing", dtype=Float32),
        Field(name="ai_ml", dtype=Float32),
        Field(name="communication", dtype=Float32),
        Field(name="problem_solving", dtype=Float32),
        Field(name="teamwork", dtype=Float32),
        Field(name="internship", dtype=Int64),
        Field(name="projects", dtype=Int64),
        Field(name="certifications", dtype=Int64),
        Field(name="aptitude", dtype=Float32),
        Field(name="average_skill", dtype=Float32),
        Field(name="industry_requirement", dtype=Float32),
        Field(name="skill_gap", dtype=Float32)
    ],

    source=employability_source,

    online=True
)

employability_feature_service = FeatureService(
    name="employability_prediction_service",
    features=[
        employability_feature_view
    ]
)
'''

with open(
    f"{repo_path}/features.py",
    "w"
) as f:
    f.write(feature_definition)

In [22]:
!find /content/employability_feast -maxdepth 2 -type f

/content/employability_feast/data/employability_features.parquet
/content/employability_feast/features.py
/content/employability_feast/feature_store.yaml

In [23]:
%cd /content/employability_feast

/content/employability_feast

In [24]:
!feast apply

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/content/employability_feast/features.py:17: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity 'student'.
  student = Entity(
No project found in the repository. Using project name employability_project defined in feature_store.yaml
Applying changes for project employability_project
Created project employability_project
Created entity student
Created feature view employability_features
Created feature service employability_prediction_service

Created sqlite table employability_project_employability_features

In [25]:
!feast entities list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME     DESCRIPTION    TYPE
student  CSE student    ValueType.UNKNOWN

In [26]:
!feast feature-views list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME                    ENTITIES     TYPE         ENABLED    STATE
employability_features  {'student'}  FeatureView  Yes        STATE_UNSPECIFIED

In [30]:
from feast import FeatureStore
store = FeatureStore(repo_path="/content/employability_feast")

In [31]:
feature_service = store.get_feature_service("employability_prediction_service")

In [32]:
entity_df = label_df.copy()
display(entity_df.head())

   student_id           event_timestamp  employability
0        1001 2026-01-01 00:16:41+00:00              0
1        1002 2026-01-01 00:16:42+00:00              1
2        1003 2026-01-01 00:16:43+00:00              1
3        1004 2026-01-01 00:16:44+00:00              1
4        1005 2026-01-01 00:16:45+00:00              0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [33]:
training_data = store.get_historical_features(entity_df=entity_df,features=feature_service).to_df()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [34]:
display(training_data.head())

,student_id,event_timestamp,employability,gender_encoded,cgpa,attendance,programming,data_structures,algorithms,dbms,...,communication,problem_solving,teamwork,internship,projects,certifications,aptitude,average_skill,industry_requirement,skill_gap
0,1001,2026-01-01 00:16:41+00:00,0,0,8.14,84.0,41.0,47.0,49.0,92.0,...,45.0,49.0,85.0,0,2,2,98.0,69.529999,89.0,19.469999
1,1002,2026-01-01 00:16:42+00:00,1,0,8.85,95.0,88.0,52.0,73.0,84.0,...,95.0,63.0,63.0,0,4,5,58.0,74.940002,87.0,12.060000
2,1003,2026-01-01 00:16:43+00:00,1,0,7.44,86.0,52.0,47.0,55.0,51.0,...,81.0,57.0,73.0,1,5,2,100.0,66.180000,86.0,19.820000
3,1004,2026-01-01 00:16:44+00:00,1,0,6.07,97.0,43.0,96.0,87.0,100.0,...,68.0,88.0,85.0,0,3,0,99.0,74.180000,75.0,0.820000
4,1005,2026-01-01 00:16:45+00:00,0,0,6.78,66.0,65.0,62.0,90.0,87.0,...,54.0,57.0,61.0,0,2,4,72.0,67.820000,77.0,9.180000

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)