<a href="https://colab.research.google.com/github/Geetanjali501/231FA04501_ML-OPS/blob/main/MLops_Feast_cla-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install feast==0.64.0 pyarrow "tenacity>=9,<10"

Collecting feast==0.64.0
  Downloading feast-0.64.0-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)
Requirement already satisfied: tenacity<10,>=9 in /usr/local/lib/python3.12/dist-packages (9.1.4)
Requirement already satisfied: click<9.0.0,>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from feast==0.64.0) (8.4.2)
Collecting colorama<1,>=0.3.9 (from feast==0.64.0)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: dill~=0.3.0 in /usr/local/lib/python3.12/dist-packages (from feast==0.64.0) (0.3.8)
Requirement already satisfied: protobuf>=4.24.0 in /usr/local/lib/python3.12/dist-packages (from feast==0.64.0) (5.29.6)
Requirement already satisfied: Jinja2<4,>=2 in /usr/local/lib/python3.12/dist-packages (from feast==0.64.0) (3.1.6)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.12/dist-packages (from feast==0.64.0) (4.26.0)
Requirement already satisfied: mmh3 in /usr/local/lib/python3.12/dist-packages (from feast==0.64.0) (5.2.1)
Requirement already satisfied: numpy<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from feast==0.64.0) (2.0.2)
Requirement already satisfied: pandas<3,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from feast==0.64.0) (2.2.2)
Collecting pyarrow
  Downloading pyarrow-25.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: pydantic>=2.10.6 in /usr/local/lib/python3.12/dist-packages (from feast==0.64.0) (2.13.4)
Requirement already satisfied: pygments<3,>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from feast==0.64.0) (2.20.0)
Requirement already satisfied: PyYAML<7,>=5.4.0 in /usr/local/lib/python3.12/dist-packages (from feast==0.64.0) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from feast==0.64.0) (2.32.4)
Requirement already satisfied: SQLAlchemy>1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy[mypy]>1->feast==0.64.0) (2.0.51)
Requirement already satisfied: tabulate<1,>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from feast==0.64.0) (0.9.0)
INFO: pip is looking at multiple versions of feast to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install feast==0.64.0 and tenacity<10 and >=9 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested tenacity<10 and >=9
    feast 0.64.0 depends on tenacity<9 and >=7

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

In [ ]:
import feast
print("Feast version:", feast.__version__)

Feast version: 0.64.0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving balanced_employability_dataset.csv to balanced_employability_dataset.csv

In [ ]:
import pandas as pd
df = pd.read_csv("balanced_employability_dataset.csv")
print(df.head())
print(df.shape)

   Student_ID  Age  Gender  CGPA  Attendance  Programming  Data_Structures  \
0        1001   23       1  8.14          84           41               47
1        1002   24       1  8.85          95           88               52
2        1003   22       1  7.44          86           52               47
3        1004   24       0  6.07          97           43               96
4        1005   24       1  6.78          66           65               62

   Algorithms  DBMS  Operating_Systems  ...  Problem_Solving  Teamwork  \
0          49    92                 47  ...               49        85
1          73    84                 93  ...               63        63
2          55    51                 91  ...               57        73
3          87   100                 59  ...               88        85
4          90    87                 71  ...               57        61

   Internship  Projects  Certifications  Aptitude  Average_Skill  \
0           0         2               2        98          69.53
1           0         4               5        58          74.94
2           1         5               2       100          66.18
3           0         3               0        99          74.18
4           0         2               4        72          67.82

   Industry_Requirement  Skill_Gap  Employability
0                    89      19.47              0
1                    87      12.06              1
2                    86      19.82              1
3                    75       0.82              1
4                    77       9.18              0

[5 rows x 30 columns]
(694, 30)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
print(df.columns)
print(df.info())
print(df.isnull().sum())

Index(['Student_ID', 'Age', 'Gender', 'CGPA', 'Attendance', 'Programming',
       'Data_Structures', 'Algorithms', 'DBMS', 'Operating_Systems',
       'Computer_Networks', 'OOP', 'Python', 'Java', 'SQL', 'Web_Development',
       'Git_GitHub', 'Cloud_Computing', 'AI_ML', 'Communication',
       'Problem_Solving', 'Teamwork', 'Internship', 'Projects',
       'Certifications', 'Aptitude', 'Average_Skill', 'Industry_Requirement',
       'Skill_Gap', 'Employability'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 694 entries, 0 to 693
Data columns (total 30 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Student_ID            694 non-null    int64
 1   Age                   694 non-null    int64
 2   Gender                694 non-null    int64
 3   CGPA                  694 non-null    float64
 4   Attendance            694 non-null    int64
 5   Programming           694 non-null    int64
 6   Data_Structures       694 non-null    int64
 7   Algorithms            694 non-null    int64
 8   DBMS                  694 non-null    int64
 9   Operating_Systems     694 non-null    int64
 10  Computer_Networks     694 non-null    int64
 11  OOP                   694 non-null    int64
 12  Python                694 non-null    int64
 13  Java                  694 non-null    int64
 14  SQL                   694 non-null    int64
 15  Web_Development       694 non-null    int64
 16  Git_GitHub            694 non-null    int64
 17  Cloud_Computing       694 non-null    int64
 18  AI_ML                 694 non-null    int64
 19  Communication         694 non-null    int64
 20  Problem_Solving       694 non-null    int64
 21  Teamwork              694 non-null    int64
 22  Internship            694 non-null    int64
 23  Projects              694 non-null    int64
 24  Certifications        694 non-null    int64
 25  Aptitude              694 non-null    int64
 26  Average_Skill         694 non-null    float64
 27  Industry_Requirement  694 non-null    int64
 28  Skill_Gap             694 non-null    float64
 29  Employability         694 non-null    int64
dtypes: float64(3), int64(27)
memory usage: 162.8 KB
None
Student_ID              0
Age                     0
Gender                  0
CGPA                    0
Attendance              0
Programming             0
Data_Structures         0
Algorithms              0
DBMS                    0
Operating_Systems       0
Computer_Networks       0
OOP                     0
Python                  0
Java                    0
SQL                     0
Web_Development         0
Git_GitHub              0
Cloud_Computing         0
AI_ML                   0
Communication           0
Problem_Solving         0
Teamwork                0
Internship              0
Projects                0
Certifications          0
Aptitude                0
Average_Skill           0
Industry_Requirement    0
Skill_Gap               0
Employability           0
dtype: int64

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
import pandas as pd

df["student_id"] = df["Student_ID"].astype("int64")

df["cgpa"] = df["CGPA"].astype("float32")
df["attendance"] = df["Attendance"].astype("float32")

df["programming"] = df["Programming"].astype("float32")
df["data_structures"] = df["Data_Structures"].astype("float32")
df["algorithms"] = df["Algorithms"].astype("float32")
df["dbms"] = df["DBMS"].astype("float32")
df["operating_systems"] = df["Operating_Systems"].astype("float32")
df["computer_networks"] = df["Computer_Networks"].astype("float32")
df["oop"] = df["OOP"].astype("float32")
df["python"] = df["Python"].astype("float32")
df["java"] = df["Java"].astype("float32")
df["sql"] = df["SQL"].astype("float32")
df["web_development"] = df["Web_Development"].astype("float32")

df["git_github"] = df["Git_GitHub"].astype("float32")
df["cloud_computing"] = df["Cloud_Computing"].astype("float32")
df["ai_ml"] = df["AI_ML"].astype("float32")

df["communication"] = df["Communication"].astype("float32")
df["problem_solving"] = df["Problem_Solving"].astype("float32")
df["teamwork"] = df["Teamwork"].astype("float32")

df["internship"] = df["Internship"].astype("int64")
df["projects"] = df["Projects"].astype("int64")
df["certifications"] = df["Certifications"].astype("int64")
df["aptitude"] = df["Aptitude"].astype("float32")

df["average_skill"] = df["Average_Skill"].astype("float32")
df["industry_requirement"] = df["Industry_Requirement"].astype("float32")
df["skill_gap"] = df["Skill_Gap"].astype("float32")

df["Gender"] = df["Gender"].astype(str).str.strip().str.lower()

df["gender_encoded"] = df["Gender"].map({
    "male": 0,
    "female": 1
})

df["gender_encoded"] = df["gender_encoded"].fillna(0).astype("int64")

df["employability"] = df["Employability"].astype("int64")

print(df.head())

   Student_ID  Age Gender  CGPA  Attendance  Programming  Data_Structures  \
0        1001   23      1  8.14          84           41               47
1        1002   24      1  8.85          95           88               52
2        1003   22      1  7.44          86           52               47
3        1004   24      0  6.07          97           43               96
4        1005   24      1  6.78          66           65               62

   Algorithms  DBMS  Operating_Systems  ...  teamwork  internship  projects  \
0          49    92                 47  ...      85.0           0         2
1          73    84                 93  ...      63.0           0         4
2          55    51                 91  ...      73.0           1         5
3          87   100                 59  ...      85.0           0         3
4          90    87                 71  ...      61.0           0         2

   certifications  aptitude  average_skill  industry_requirement  skill_gap  \
0               2      98.0      69.529999                  89.0  19.469999
1               5      58.0      74.940002                  87.0  12.060000
2               2     100.0      66.180000                  86.0  19.820000
3               0      99.0      74.180000                  75.0   0.820000
4               4      72.0      67.820000                  77.0   9.180000

   gender_encoded  employability
0               0              0
1               0              1
2               0              1
3               0              1
4               0              0

[5 rows x 59 columns]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
df[
    [
        "student_id",
        "gender_encoded",
        "cgpa",
        "attendance",
        "programming",
        "data_structures",
        "algorithms",
        "dbms",
        "operating_systems",
        "computer_networks",
        "oop",
        "python",
        "java",
        "sql",
        "web_development",
        "git_github",
        "cloud_computing",
        "ai_ml",
        "communication",
        "problem_solving",
        "teamwork",
        "internship",
        "projects",
        "certifications",
        "aptitude",
        "average_skill",
        "industry_requirement",
        "skill_gap",
        "employability"
    ]
].head()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,student_id,gender_encoded,cgpa,attendance,programming,data_structures,algorithms,dbms,operating_systems,computer_networks,...,problem_solving,teamwork,internship,projects,certifications,aptitude,average_skill,industry_requirement,skill_gap,employability
0,1001,0,8.14,84.0,41.0,47.0,49.0,92.0,47.0,92.0,...,49.0,85.0,0,2,2,98.0,69.529999,89.0,19.469999,0
1,1002,0,8.85,95.0,88.0,52.0,73.0,84.0,93.0,69.0,...,63.0,63.0,0,4,5,58.0,74.940002,87.0,12.060000,1
2,1003,0,7.44,86.0,52.0,47.0,55.0,51.0,91.0,74.0,...,57.0,73.0,1,5,2,100.0,66.180000,86.0,19.820000,1
3,1004,0,6.07,97.0,43.0,96.0,87.0,100.0,59.0,74.0,...,88.0,85.0,0,3,0,99.0,74.180000,75.0,0.820000,1
4,1005,0,6.78,66.0,65.0,62.0,90.0,87.0,71.0,88.0,...,57.0,61.0,0,2,4,72.0,67.820000,77.0,9.180000,0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
base_time = pd.Timestamp(
    "2026-01-01",
    tz="UTC"
)

df["event_timestamp"] = (
    base_time +
    pd.to_timedelta(
        df["student_id"],
        unit="s"
    )
)

df["created_timestamp"] = (
    df["event_timestamp"] +
    pd.Timedelta(seconds=1)
)

In [ ]:
feature_df = df[
    [
        "student_id",
        "event_timestamp",
        "created_timestamp",
        "gender_encoded",
        "cgpa",
        "attendance",
        "programming",
        "data_structures",
        "algorithms",
        "dbms",
        "operating_systems",
        "computer_networks",
        "oop",
        "python",
        "java",
        "sql",
        "web_development",
        "git_github",
        "cloud_computing",
        "ai_ml",
        "communication",
        "problem_solving",
        "teamwork",
        "internship",
        "projects",
        "certifications",
        "aptitude",
        "average_skill",
        "industry_requirement",
        "skill_gap"
    ]
].copy()

label_df = df[
    [
        "student_id",
        "event_timestamp",
        "employability"
    ]
].copy()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
print("Feature data:")
display(feature_df.head())
print("Labels:")
display(label_df.head())

Feature data:

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,student_id,event_timestamp,created_timestamp,gender_encoded,cgpa,attendance,programming,data_structures,algorithms,dbms,...,communication,problem_solving,teamwork,internship,projects,certifications,aptitude,average_skill,industry_requirement,skill_gap
0,1001,2026-01-01 00:16:41+00:00,2026-01-01 00:16:42+00:00,0,8.14,84.0,41.0,47.0,49.0,92.0,...,45.0,49.0,85.0,0,2,2,98.0,69.529999,89.0,19.469999
1,1002,2026-01-01 00:16:42+00:00,2026-01-01 00:16:43+00:00,0,8.85,95.0,88.0,52.0,73.0,84.0,...,95.0,63.0,63.0,0,4,5,58.0,74.940002,87.0,12.060000
2,1003,2026-01-01 00:16:43+00:00,2026-01-01 00:16:44+00:00,0,7.44,86.0,52.0,47.0,55.0,51.0,...,81.0,57.0,73.0,1,5,2,100.0,66.180000,86.0,19.820000
3,1004,2026-01-01 00:16:44+00:00,2026-01-01 00:16:45+00:00,0,6.07,97.0,43.0,96.0,87.0,100.0,...,68.0,88.0,85.0,0,3,0,99.0,74.180000,75.0,0.820000
4,1005,2026-01-01 00:16:45+00:00,2026-01-01 00:16:46+00:00,0,6.78,66.0,65.0,62.0,90.0,87.0,...,54.0,57.0,61.0,0,2,4,72.0,67.820000,77.0,9.180000

Labels:

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

   student_id           event_timestamp  employability
0        1001 2026-01-01 00:16:41+00:00              0
1        1002 2026-01-01 00:16:42+00:00              1
2        1003 2026-01-01 00:16:43+00:00              1
3        1004 2026-01-01 00:16:44+00:00              1
4        1005 2026-01-01 00:16:45+00:00              0

In [ ]:
import os

repo_path = "/content/employability_feast"

os.makedirs(
    f"{repo_path}/data",
    exist_ok=True
)

In [ ]:
feature_df.to_parquet(
    f"{repo_path}/data/employability_features.parquet",
    index=False
)

In [ ]:
feature_store_yaml = """
project: employability_project

registry: data/registry.db

provider: local

offline_store:
  type: file

online_store:
  type: sqlite
  path: data/online_store.db
"""

with open(
    f"{repo_path}/feature_store.yaml",
    "w"
) as f:
    f.write(feature_store_yaml)

In [ ]:
feature_definition = '''
from datetime import timedelta

from feast import (
    Entity,
    FeatureView,
    FeatureService,
    Field,
    FileSource
)

from feast.types import (
    Float32,
    Int64
)

student = Entity(
    name="student",
    join_keys=["student_id"],
    description="CSE student"
)

employability_source = FileSource(
    name="employability_source",
    path="data/employability_features.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp"
)

employability_feature_view = FeatureView(
    name="employability_features",
    entities=[student],

    ttl=timedelta(days=50000),

    schema=[
        Field(name="gender_encoded", dtype=Int64),
        Field(name="cgpa", dtype=Float32),
        Field(name="attendance", dtype=Float32),
        Field(name="programming", dtype=Float32),
        Field(name="data_structures", dtype=Float32),
        Field(name="algorithms", dtype=Float32),
        Field(name="dbms", dtype=Float32),
        Field(name="operating_systems", dtype=Float32),
        Field(name="computer_networks", dtype=Float32),
        Field(name="oop", dtype=Float32),
        Field(name="python", dtype=Float32),
        Field(name="java", dtype=Float32),
        Field(name="sql", dtype=Float32),
        Field(name="web_development", dtype=Float32),
        Field(name="git_github", dtype=Float32),
        Field(name="cloud_computing", dtype=Float32),
        Field(name="ai_ml", dtype=Float32),
        Field(name="communication", dtype=Float32),
        Field(name="problem_solving", dtype=Float32),
        Field(name="teamwork", dtype=Float32),
        Field(name="internship", dtype=Int64),
        Field(name="projects", dtype=Int64),
        Field(name="certifications", dtype=Int64),
        Field(name="aptitude", dtype=Float32),
        Field(name="average_skill", dtype=Float32),
        Field(name="industry_requirement", dtype=Float32),
        Field(name="skill_gap", dtype=Float32)
    ],

    source=employability_source,

    online=True
)

employability_feature_service = FeatureService(
    name="employability_prediction_service",
    features=[
        employability_feature_view
    ]
)
'''

with open(
    f"{repo_path}/features.py",
    "w"
) as f:
    f.write(feature_definition)

In [ ]:
!find /content/employability_feast -maxdepth 2 -type f

/content/employability_feast/data/employability_features.parquet
/content/employability_feast/features.py
/content/employability_feast/feature_store.yaml

In [ ]:
%cd /content/employability_feast

/content/employability_feast

In [ ]:
!feast apply

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/content/employability_feast/features.py:17: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity 'student'.
  student = Entity(
No project found in the repository. Using project name employability_project defined in feature_store.yaml
Applying changes for project employability_project
Created project employability_project
Created entity student
Created feature view employability_features
Created feature service employability_prediction_service

Created sqlite table employability_project_employability_features

In [ ]:
!feast entities list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME     DESCRIPTION    TYPE
student  CSE student    ValueType.UNKNOWN

In [ ]:
!feast feature-views list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME                    ENTITIES     TYPE         ENABLED    STATE
employability_features  {'student'}  FeatureView  Yes        STATE_UNSPECIFIED

In [ ]:
from feast import FeatureStore
store = FeatureStore(repo_path="/content/employability_feast")

In [ ]:
feature_service = store.get_feature_service("employability_prediction_service")

In [ ]:
entity_df = label_df.copy()
display(entity_df.head())

   student_id           event_timestamp  employability
0        1001 2026-01-01 00:16:41+00:00              0
1        1002 2026-01-01 00:16:42+00:00              1
2        1003 2026-01-01 00:16:43+00:00              1
3        1004 2026-01-01 00:16:44+00:00              1
4        1005 2026-01-01 00:16:45+00:00              0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
training_data = store.get_historical_features(entity_df=entity_df,features=feature_service).to_df()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
display(training_data.head())

,student_id,event_timestamp,employability,gender_encoded,cgpa,attendance,programming,data_structures,algorithms,dbms,...,communication,problem_solving,teamwork,internship,projects,certifications,aptitude,average_skill,industry_requirement,skill_gap
0,1001,2026-01-01 00:16:41+00:00,0,0,8.14,84.0,41.0,47.0,49.0,92.0,...,45.0,49.0,85.0,0,2,2,98.0,69.529999,89.0,19.469999
1,1002,2026-01-01 00:16:42+00:00,1,0,8.85,95.0,88.0,52.0,73.0,84.0,...,95.0,63.0,63.0,0,4,5,58.0,74.940002,87.0,12.060000
2,1003,2026-01-01 00:16:43+00:00,1,0,7.44,86.0,52.0,47.0,55.0,51.0,...,81.0,57.0,73.0,1,5,2,100.0,66.180000,86.0,19.820000
3,1004,2026-01-01 00:16:44+00:00,1,0,6.07,97.0,43.0,96.0,87.0,100.0,...,68.0,88.0,85.0,0,3,0,99.0,74.180000,75.0,0.820000
4,1005,2026-01-01 00:16:45+00:00,0,0,6.78,66.0,65.0,62.0,90.0,87.0,...,54.0,57.0,61.0,0,2,4,72.0,67.820000,77.0,9.180000

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
!pip install feast

Collecting feast
  Downloading feast-0.65.0-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: attrs in /usr/local/lib/python3.12/dist-packages (from feast) (26.1.0)
Requirement already satisfied: click<9.0.0,>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from feast) (8.4.2)
Collecting colorama<1,>=0.3.9 (from feast)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: dill~=0.3.0 in /usr/local/lib/python3.12/dist-packages (from feast) (0.3.8)
Requirement already satisfied: protobuf>=4.24.0 in /usr/local/lib/python3.12/dist-packages (from feast) (5.29.6)
Requirement already satisfied: Jinja2<4,>=2 in /usr/local/lib/python3.12/dist-packages (from feast) (3.1.6)
Requirement already satisfied: mmh3 in /usr/local/lib/python3.12/dist-packages (from feast) (5.2.1)
Requirement already satisfied: numpy<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from feast) (2.0.2)
Requirement already satisfied: pandas<3,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from feast) (2.2.2)
Requirement already satisfied: pyarrow>=16.1.0 in /usr/local/lib/python3.12/dist-packages (from feast) (18.1.0)
Requirement already satisfied: pydantic>=2.10.6 in /usr/local/lib/python3.12/dist-packages (from feast) (2.13.4)
Requirement already satisfied: pygments<3,>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from feast) (2.20.0)
Requirement already satisfied: PyYAML<7,>=5.4.0 in /usr/local/lib/python3.12/dist-packages (from feast) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from feast) (2.32.4)
Requirement already satisfied: SQLAlchemy>1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy[mypy]>1->feast) (2.0.51)
Requirement already satisfied: tabulate<1,>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from feast) (0.9.0)
Collecting tenacity<9,>=7 (from feast)
  Downloading tenacity-8.5.0-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: toml<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from feast) (0.10.2)
Requirement already satisfied: tqdm<5,>=4 in /usr/local/lib/python3.12/dist-packages (from feast) (4.67.3)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from feast) (4.5.2)
Requirement already satisfied: fastapi>=0.68.0 in /usr/local/lib/python3.12/dist-packages (from feast) (0.139.0)
Requirement already satisfied: starlette>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from feast) (1.3.1)
Collecting uvicorn<=0.34.0,>=0.30.6 (from uvicorn[standard]<=0.34.0,>=0.30.6->feast)
  Downloading uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)
Collecting uvicorn-worker (from feast)
  Downloading uvicorn_worker-0.4.0-py3-none-any.whl.metadata (2.6 kB)
Collecting gunicorn (from feast)
  Downloading gunicorn-26.0.0-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: dask>=2024.2.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]>=2024.2.1->feast) (2026.7.0)
Collecting prometheus_client<0.25.0,>=0.20.0 (from feast)
  Downloading prometheus_client-0.24.1-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from feast) (5.9.5)
Collecting bigtree>=0.19.2 (from feast)
  Downloading bigtree-1.5.3-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pyjwt in /usr/local/lib/python3.12/dist-packages (from feast) (2.13.0)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (26.2)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (1.4.2)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (0.12.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.68.0->feast) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.68.0->feast) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.68.0->feast) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2<4,>=2->feast) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.3->feast) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.3->feast) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.3->feast) (2026.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.10.6->feast) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.10.6->feast) (2.46.4)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy>1->SQLAlchemy[mypy]>1->feast) (3.5.3)
Collecting mypy>=0.910 (from SQLAlchemy[mypy]>1->feast)
  Downloading mypy-2.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette>=1.0.1->feast) (4.14.2)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<=0.34.0,>=0.30.6->uvicorn[standard]<=0.34.0,>=0.30.6->feast) (0.16.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (0.8.0)
Requirement already satisfied: python-dotenv>=0.13 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (1.2.2)
Requirement already satisfied: uvloop!=0.15.0,!=0.15.1,>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (0.22.1)
Requirement already satisfied: watchfiles>=0.13 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (1.2.0)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (15.0.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->feast) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->feast) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->feast) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->feast) (2026.6.17)
INFO: pip is looking at multiple versions of uvicorn-worker to determine which version is compatible with other requirements. This could take a while.
Collecting uvicorn-worker (from feast)
  Downloading uvicorn_worker-0.3.0-py3-none-any.whl.metadata (2.6 kB)
Collecting mypy_extensions>=1.0.0 (from mypy>=0.910->SQLAlchemy[mypy]>1->feast)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting pathspec>=1.0.0 (from mypy>=0.910->SQLAlchemy[mypy]>1->feast)
  Downloading pathspec-1.1.1-py3-none-any.whl.metadata (14 kB)
Collecting librt>=0.13.0 (from mypy>=0.910->SQLAlchemy[mypy]>1->feast)
  Downloading librt-0.15.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.3 kB)
Collecting ast-serialize<1.0.0,>=0.6.0 (from mypy>=0.910->SQLAlchemy[mypy]>1->feast)
  Downloading ast_serialize-0.8.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (1.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.3->feast) (1.17.0)
Downloading feast-0.65.0-py3-none-any.whl (9.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 83.4 MB/s eta 0:00:00
Downloading bigtree-1.5.3-py3-none-any.whl (137 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.2/137.2 kB 13.4 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading prometheus_client-0.24.1-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 5.0 MB/s eta 0:00:00
Downloading tenacity-8.5.0-py3-none-any.whl (28 kB)
Downloading uvicorn-0.34.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 6.1 MB/s eta 0:00:00
Downloading gunicorn-26.0.0-py3-none-any.whl (212 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 20.9 MB/s eta 0:00:00
Downloading uvicorn_worker-0.3.0-py3-none-any.whl (5.3 kB)
Downloading mypy-2.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (15.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 84.4 MB/s eta 0:00:00
Downloading ast_serialize-0.8.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 75.0 MB/s eta 0:00:00
Downloading librt-0.15.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (531 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 kB 40.7 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading pathspec-1.1.1-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 5.5 MB/s eta 0:00:00
Installing collected packages: uvicorn, tenacity, prometheus_client, pathspec, mypy_extensions, librt, gunicorn, colorama, bigtree, ast-serialize, uvicorn-worker, mypy, feast
  Attempting uninstall: uvicorn
    Found existing installation: uvicorn 0.51.0
    Uninstalling uvicorn-0.51.0:
      Successfully uninstalled uvicorn-0.51.0
  Attempting uninstall: tenacity
    Found existing installation: tenacity 9.1.4
    Uninstalling tenacity-9.1.4:
      Successfully uninstalled tenacity-9.1.4
  Attempting uninstall: prometheus_client
    Found existing installation: prometheus_client 0.25.0
    Uninstalling prometheus_client-0.25.0:
      Successfully uninstalled prometheus_client-0.25.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.4.0 requires tenacity<10,>=9, but you have tenacity 8.5.0 which is incompatible.
Successfully installed ast-serialize-0.8.0 bigtree-1.5.3 colorama-0.4.6 feast-0.65.0 gunicorn-26.0.0 librt-0.15.0 mypy-2.3.1 mypy_extensions-1.1.0 pathspec-1.1.1 prometheus_client-0.24.1 tenacity-8.5.0 uvicorn-0.34.0 uvicorn-worker-0.3.0

In [ ]:
!feast --version

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
Usage: feast [OPTIONS] COMMAND [ARGS]...
Try 'feast --help' for help.

Error: No such option '--version'.

In [ ]:
!find /content -maxdepth 3 -type f \( -name "feature_store.yaml" -o -name "features.py" \) -print

In [ ]:
repo_path = "/content/employability_feast"

In [ ]:
!pip install -q feast==0.64.0 pyarrow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 15.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 18.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.2/137.2 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 17.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 87.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 70.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 kB 36.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 4.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.4.0 requires tenacity<10,>=9, but you have tenacity 8.5.0 which is incompatible.

In [ ]:
import feast
print("Feast version:", feast.__version__)

Feast version: 0.64.0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
repo_path = "/content/employability_feast"

In [ ]:
import os
import pandas as pd

df = pd.read_csv("balanced_employability_dataset.csv")

df["student_id"] = df["Student_ID"].astype("int64")
df["cgpa"] = df["CGPA"].astype("float32")
df["attendance"] = df["Attendance"].astype("float32")

df["programming"] = df["Programming"].astype("float32")
df["data_structures"] = df["Data_Structures"].astype("float32")
df["algorithms"] = df["Algorithms"].astype("float32")
df["dbms"] = df["DBMS"].astype("float32")
df["operating_systems"] = df["Operating_Systems"].astype("float32")
df["computer_networks"] = df["Computer_Networks"].astype("float32")
df["oop"] = df["OOP"].astype("float32")
df["python"] = df["Python"].astype("float32")
df["java"] = df["Java"].astype("float32")
df["sql"] = df["SQL"].astype("float32")
df["web_development"] = df["Web_Development"].astype("float32")
df["git_github"] = df["Git_GitHub"].astype("float32")
df["cloud_computing"] = df["Cloud_Computing"].astype("float32")
df["ai_ml"] = df["AI_ML"].astype("float32")

df["communication"] = df["Communication"].astype("float32")
df["problem_solving"] = df["Problem_Solving"].astype("float32")
df["teamwork"] = df["Teamwork"].astype("float32")

df["internship"] = df["Internship"].astype("int64")
df["projects"] = df["Projects"].astype("int64")
df["certifications"] = df["Certifications"].astype("int64")
df["aptitude"] = df["Aptitude"].astype("float32")

df["average_skill"] = df["Average_Skill"].astype("float32")
df["industry_requirement"] = df["Industry_Requirement"].astype("float32")
df["skill_gap"] = df["Skill_Gap"].astype("float32")

df["Gender"] = df["Gender"].astype(str).str.strip().str.lower()
df["gender_encoded"] = df["Gender"].map({
    "male": 0,
    "female": 1
}).fillna(0).astype("int64")

df["employability"] = df["Employability"].astype("int64")

base_time = pd.Timestamp("2026-01-01", tz="UTC")

df["event_timestamp"] = (
    base_time + pd.to_timedelta(df["student_id"], unit="s")
)

df["created_timestamp"] = (
    df["event_timestamp"] + pd.Timedelta(seconds=1)
)

feature_columns = [
    "student_id",
    "event_timestamp",
    "created_timestamp",
    "gender_encoded",
    "cgpa",
    "attendance",
    "programming",
    "data_structures",
    "algorithms",
    "dbms",
    "operating_systems",
    "computer_networks",
    "oop",
    "python",
    "java",
    "sql",
    "web_development",
    "git_github",
    "cloud_computing",
    "ai_ml",
    "communication",
    "problem_solving",
    "teamwork",
    "internship",
    "projects",
    "certifications",
    "aptitude",
    "average_skill",
    "industry_requirement",
    "skill_gap"
]

feature_df = df[feature_columns].copy()

label_df = df[
    ["student_id", "event_timestamp", "employability"]
].copy()

repo_path = "/content/employability_feast"

os.makedirs(f"{repo_path}/data", exist_ok=True)

feature_df.to_parquet(
    f"{repo_path}/data/employability_features.parquet",
    index=False
)

feature_store_yaml = """
project: employability_project

registry: data/registry.db

provider: local

offline_store:
  type: file

online_store:
  type: sqlite
  path: data/online_store.db
"""

with open(f"{repo_path}/feature_store.yaml", "w") as f:
    f.write(feature_store_yaml)

print("Feast repository created successfully!")
print(repo_path)

FileNotFoundError: [Errno 2] No such file or directory: 'balanced_employability_dataset.csv'

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving balanced_employability_dataset.csv to balanced_employability_dataset.csv

In [ ]:
import os
print(os.listdir("/content"))

['.config', 'balanced_employability_dataset.csv', 'sample_data']

In [ ]:
import os
import pandas as pd

df = pd.read_csv("balanced_employability_dataset.csv")

df["student_id"] = df["Student_ID"].astype("int64")
df["cgpa"] = df["CGPA"].astype("float32")
df["attendance"] = df["Attendance"].astype("float32")

df["programming"] = df["Programming"].astype("float32")
df["data_structures"] = df["Data_Structures"].astype("float32")
df["algorithms"] = df["Algorithms"].astype("float32")
df["dbms"] = df["DBMS"].astype("float32")
df["operating_systems"] = df["Operating_Systems"].astype("float32")
df["computer_networks"] = df["Computer_Networks"].astype("float32")
df["oop"] = df["OOP"].astype("float32")
df["python"] = df["Python"].astype("float32")
df["java"] = df["Java"].astype("float32")
df["sql"] = df["SQL"].astype("float32")
df["web_development"] = df["Web_Development"].astype("float32")
df["git_github"] = df["Git_GitHub"].astype("float32")
df["cloud_computing"] = df["Cloud_Computing"].astype("float32")
df["ai_ml"] = df["AI_ML"].astype("float32")

df["communication"] = df["Communication"].astype("float32")
df["problem_solving"] = df["Problem_Solving"].astype("float32")
df["teamwork"] = df["Teamwork"].astype("float32")

df["internship"] = df["Internship"].astype("int64")
df["projects"] = df["Projects"].astype("int64")
df["certifications"] = df["Certifications"].astype("int64")
df["aptitude"] = df["Aptitude"].astype("float32")

df["average_skill"] = df["Average_Skill"].astype("float32")
df["industry_requirement"] = df["Industry_Requirement"].astype("float32")
df["skill_gap"] = df["Skill_Gap"].astype("float32")

df["Gender"] = df["Gender"].astype(str).str.strip().str.lower()
df["gender_encoded"] = df["Gender"].map({
    "male": 0,
    "female": 1
}).fillna(0).astype("int64")

df["employability"] = df["Employability"].astype("int64")

base_time = pd.Timestamp("2026-01-01", tz="UTC")

df["event_timestamp"] = (
    base_time + pd.to_timedelta(df["student_id"], unit="s")
)

df["created_timestamp"] = (
    df["event_timestamp"] + pd.Timedelta(seconds=1)
)

feature_columns = [
    "student_id",
    "event_timestamp",
    "created_timestamp",
    "gender_encoded",
    "cgpa",
    "attendance",
    "programming",
    "data_structures",
    "algorithms",
    "dbms",
    "operating_systems",
    "computer_networks",
    "oop",
    "python",
    "java",
    "sql",
    "web_development",
    "git_github",
    "cloud_computing",
    "ai_ml",
    "communication",
    "problem_solving",
    "teamwork",
    "internship",
    "projects",
    "certifications",
    "aptitude",
    "average_skill",
    "industry_requirement",
    "skill_gap"
]

feature_df = df[feature_columns].copy()

label_df = df[
    ["student_id", "event_timestamp", "employability"]
].copy()

repo_path = "/content/employability_feast"

os.makedirs(f"{repo_path}/data", exist_ok=True)

feature_df.to_parquet(
    f"{repo_path}/data/employability_features.parquet",
    index=False
)

feature_store_yaml = """
project: employability_project

registry: data/registry.db

provider: local

offline_store:
  type: file

online_store:
  type: sqlite
  path: data/online_store.db
"""

with open(f"{repo_path}/feature_store.yaml", "w") as f:
    f.write(feature_store_yaml)

print("Feast repository created successfully!")
print(repo_path)

Feast repository created successfully!
/content/employability_feast

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
!ls -R /content/employability_feast

/content/employability_feast:
data  feature_store.yaml

/content/employability_feast/data:
employability_features.parquet

In [ ]:
feature_definition = '''
from datetime import timedelta

from feast import (
    Entity,
    FeatureView,
    FeatureService,
    Field,
    FileSource
)

from feast.types import (
    Float32,
    Int64
)

student = Entity(
    name="student",
    join_keys=["student_id"],
    description="CSE student"
)

employability_source = FileSource(
    name="employability_source",
    path="data/employability_features.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp"
)

employability_feature_view = FeatureView(
    name="employability_features",
    entities=[student],
    ttl=timedelta(days=50000),
    schema=[
        Field(name="gender_encoded", dtype=Int64),
        Field(name="cgpa", dtype=Float32),
        Field(name="attendance", dtype=Float32),
        Field(name="programming", dtype=Float32),
        Field(name="data_structures", dtype=Float32),
        Field(name="algorithms", dtype=Float32),
        Field(name="dbms", dtype=Float32),
        Field(name="operating_systems", dtype=Float32),
        Field(name="computer_networks", dtype=Float32),
        Field(name="oop", dtype=Float32),
        Field(name="python", dtype=Float32),
        Field(name="java", dtype=Float32),
        Field(name="sql", dtype=Float32),
        Field(name="web_development", dtype=Float32),
        Field(name="git_github", dtype=Float32),
        Field(name="cloud_computing", dtype=Float32),
        Field(name="ai_ml", dtype=Float32),
        Field(name="communication", dtype=Float32),
        Field(name="problem_solving", dtype=Float32),
        Field(name="teamwork", dtype=Float32),
        Field(name="internship", dtype=Int64),
        Field(name="projects", dtype=Int64),
        Field(name="certifications", dtype=Int64),
        Field(name="aptitude", dtype=Float32),
        Field(name="average_skill", dtype=Float32),
        Field(name="industry_requirement", dtype=Float32),
        Field(name="skill_gap", dtype=Float32)
    ],
    source=employability_source,
    online=True
)

employability_feature_service = FeatureService(
    name="employability_prediction_service",
    features=[
        employability_feature_view
    ]
)
'''

with open("/content/employability_feast/features.py", "w") as f:
    f.write(feature_definition)

print("features.py created successfully!")

features.py created successfully!

In [ ]:
%cd /content/employability_feast
!feast apply

/content/employability_feast
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/content/employability_feast/features.py:17: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity 'student'.
  student = Entity(
No project found in the repository. Using project name employability_project defined in feature_store.yaml
Applying changes for project employability_project
Created project employability_project
Created entity student
Created feature view employability_features
Created feature service employability_prediction_service

Created sqlite table employability_project_employability_features

In [ ]:
!feast entities list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME     DESCRIPTION    TYPE
student  CSE student    ValueType.UNKNOWN

In [ ]:
!feast feature-views list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME                    ENTITIES     TYPE         ENABLED    STATE
employability_features  {'student'}  FeatureView  Yes        STATE_UNSPECIFIED

In [ ]:
from feast import FeatureStore

store = FeatureStore(repo_path="/content/employability_feast")

feature_service = store.get_feature_service(
    "employability_prediction_service"
)

entity_df = label_df[
    ["student_id", "event_timestamp", "employability"]
].copy()

training_data = store.get_historical_features(
    entity_df=entity_df,
    features=feature_service
).to_df()

print("Historical feature retrieval successful!")
print("Shape:", training_data.shape)

display(training_data.head())

Historical feature retrieval successful!
Shape: (500, 30)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,student_id,event_timestamp,employability,gender_encoded,cgpa,attendance,programming,data_structures,algorithms,dbms,...,communication,problem_solving,teamwork,internship,projects,certifications,aptitude,average_skill,industry_requirement,skill_gap
0,1001,2026-01-01 00:16:41+00:00,0,0,8.14,84.0,41.0,47.0,49.0,92.0,...,45.0,49.0,85.0,0,2,2,98.0,69.529999,89.0,19.469999
1,1002,2026-01-01 00:16:42+00:00,1,0,8.85,95.0,88.0,52.0,73.0,84.0,...,95.0,63.0,63.0,0,4,5,58.0,74.940002,87.0,12.060000
2,1003,2026-01-01 00:16:43+00:00,1,0,7.44,86.0,52.0,47.0,55.0,51.0,...,81.0,57.0,73.0,1,5,2,100.0,66.180000,86.0,19.820000
3,1004,2026-01-01 00:16:44+00:00,1,0,6.07,97.0,43.0,96.0,87.0,100.0,...,68.0,88.0,85.0,0,3,0,99.0,74.180000,75.0,0.820000
4,1005,2026-01-01 00:16:45+00:00,0,0,6.78,66.0,65.0,62.0,90.0,87.0,...,54.0,57.0,61.0,0,2,4,72.0,67.820000,77.0,9.180000

In [ ]:
X = training_data.drop(
    columns=["student_id", "event_timestamp", "employability"]
)

y = training_data["employability"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

display(X.head())

X shape: (500, 27)
y shape: (500,)

Target distribution:
employability
1    292
0    208
Name: count, dtype: int64

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,gender_encoded,cgpa,attendance,programming,data_structures,algorithms,dbms,operating_systems,computer_networks,oop,...,communication,problem_solving,teamwork,internship,projects,certifications,aptitude,average_skill,industry_requirement,skill_gap
0,0,8.14,84.0,41.0,47.0,49.0,92.0,47.0,92.0,86.0,...,45.0,49.0,85.0,0,2,2,98.0,69.529999,89.0,19.469999
1,0,8.85,95.0,88.0,52.0,73.0,84.0,93.0,69.0,54.0,...,95.0,63.0,63.0,0,4,5,58.0,74.940002,87.0,12.060000
2,0,7.44,86.0,52.0,47.0,55.0,51.0,91.0,74.0,43.0,...,81.0,57.0,73.0,1,5,2,100.0,66.180000,86.0,19.820000
3,0,6.07,97.0,43.0,96.0,87.0,100.0,59.0,74.0,68.0,...,68.0,88.0,85.0,0,3,0,99.0,74.180000,75.0,0.820000
4,0,6.78,66.0,65.0,62.0,90.0,87.0,71.0,88.0,98.0,...,54.0,57.0,61.0,0,2,4,72.0,67.820000,77.0,9.180000

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)
print("Training labels:", y_train.shape)
print("Testing labels:", y_test.shape)

Training data: (400, 27)
Testing data: (100, 27)
Training labels: (400,)
Testing labels: (100,)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.79

Confusion Matrix:
[[29 13]
 [ 8 50]]

Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.69      0.73        42
           1       0.79      0.86      0.83        58

    accuracy                           0.79       100
   macro avg       0.79      0.78      0.78       100
weighted avg       0.79      0.79      0.79       100

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
import joblib

model_path = "/content/employability_feast/employability_model.pkl"

joblib.dump(model, model_path)

print("Model saved successfully!")
print(model_path)

Model saved successfully!
/content/employability_feast/employability_model.pkl

In [ ]:
prediction_code = '''
import joblib
import pandas as pd

model = joblib.load("employability_model.pkl")

def predict_employability(student_features):
    data = pd.DataFrame([student_features])
    prediction = model.predict(data)[0]

    if prediction == 1:
        return "Employable"
    else:
        return "Not Employable"

print("Prediction script loaded successfully!")
'''

with open("/content/employability_feast/predict.py", "w") as f:
    f.write(prediction_code)

print("predict.py created successfully!")

predict.py created successfully!

In [ ]:
import sys

sys.path.append("/content/employability_feast")

from predict import predict_employability

print("Prediction function imported successfully!")

Prediction script loaded successfully!
Prediction function imported successfully!

In [ ]:
sample_student = X_test.iloc[0].to_dict()

result = predict_employability(sample_student)

print("Prediction:", result)

Prediction: Employable

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
!find /content/employability_feast -maxdepth 2 -type f -print

/content/employability_feast/employability_model.pkl
/content/employability_feast/predict.py
/content/employability_feast/features.py
/content/employability_feast/data/registry.db
/content/employability_feast/data/online_store.db
/content/employability_feast/data/employability_features.parquet
/content/employability_feast/__pycache__/predict.cpython-312.pyc
/content/employability_feast/feature_store.yaml

In [ ]:
%cd /content/employability_feast
!feast materialize-incremental $(date -u +"%Y-%m-%dT%H:%M:%S")

/content/employability_feast
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
Materializing 1 feature views to 2026-08-17 06:03:47+00:00 into the sqlite online store.

employability_features from 1889-09-24 06:03:58+00:00 to 2026-08-17 06:03:47+00:00:

In [ ]:
%cd /content/employability_feast

from feast import FeatureStore

store = FeatureStore(repo_path=".")

features = store.get_online_features(
    features=[
        "employability_features:cgpa",
        "employability_features:average_skill",
        "employability_features:industry_requirement",
        "employability_features:skill_gap"
    ],
    entity_rows=[
        {"student_id": 1001}
    ]
).to_dict()

print(features)

/content/employability_feast
{'student_id': [1001], 'skill_gap': [19.469999313354492], 'industry_requirement': [89.0], 'cgpa': [8.140000343322754], 'average_skill': [69.52999877929688]}